import { Metadata } from 'next';
import { ReactNode } from 'react'

type Props = {
  children: ReactNode
}

export const metadata: Metadata = {
  title: "Altern8 Admin | Projects",
  description: "Generated by create next app",
};

const Layout = ({ children }: Props) => {
  return (
    <main>
      {children}
    </main>
  )
}

export default Layout
