'use client';
import Header from '../Landing-page/Header';
import JoinUsSection from '../Landing-page/JoinUsSection';
import Footer from '../Landing-page/Footer';
import FloatingButton from '../Landing-page/FloatingButton';
import React from 'react';

const TermsCondition = () => {
  return (
    <div className="relative overflow-x-hidden [background:linear-gradient(269.75deg,_#011049,_#19112f_25.75%,_#251431_51.79%,_#301941_64.24%,_#6e3050)] w-full min-h-screen">
      <Header />
      {/* Centered Title */}
      <div className="flex flex-col items-center justify-center py-16">
        <h1 className="text-3xl font-bold text-gray-200 mb-8 mt-10">Altern8 Terms of Use</h1>

        {/* Text Area for Terms and Conditions */}
        <div className="phone:w-[90%] md:w-[70%] xl:w-[60%] xxl:w-[55%] my-10 mx-auto text-background-black-font text-lg px-6">
          <p>
            This document is an electronic record in terms of Information Technology Act, 2000 and
            rules there under as applicable and the amended provisions pertaining to electronic
            records in various statutes as amended by the Information Technology Act, 2000. This
            electronic record is generated by a computer system and does not require any physical or
            digital signature.
          </p>
          <br />
          <p>
            This document is published in accordance with the provisions of Rule 3 (1) of the
            Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing
            the rules and regulations, Privacy Policy and Terms of Use for access or usage of domain
            name ___________ including the related mobile site and mobile application (hereinafter
            referred to as “Platform”).
          </p>
          <br />
          <p>
            These terms and conditions of use ("Terms of Use") of the Platform between _________, a
            private company limited by shares incorporated under the provisions of Companies Act,
            2013 (Act No. 18 of 2013) with corporate identification number (CIN) U62099TN2024PTC169251, and
            having its registered office at 46 College Road, Nungambakkam, Chennai (hereinafter referred to as “Altern8” which
            includes the person(s)/entity(ies) associated/connected with it) and users registering
            itself/himself on the Platform ("You" or "Your" or "Yourself" or "User") describe the
            terms on which Altern8 offers You access to the Platform and the Services (as defined
            below) through the Platform.
          </p>
          <br />
          <p>
            Please read the Terms of Use carefully before using or registering on the Platform or
            accessing any material, information or services through the Platform. Accessing,
            browsing or otherwise using the Platform indicates Your agreement to all the terms and
            conditions under this Terms of Use and Your agreement to be legally bound by them.
          </p>
          <br />
          <p>
            By implicitly or expressly accepting these Terms of Use, You also accept and agree to be
            bound by all Altern8 Policies (including but not limited to the Privacy Policy available
            on our Platform as amended from time to time).
          </p>
          <br />
          <p>
            If you do not agree to these terms, you agree that your sole and exclusive remedy is to
            discontinue using the Platform. Your compliance with these terms is a condition to your
            right to access the Platform. Your breach of any provision of these terms will
            automatically, without the requirement of notice or other action, revoke and terminate
            your right to access the Platform.
          </p>
          <br />
          <h2 className="font-bold mt-4">• General</h2>
          <br />
          <p>
            Our platform is essentially an internet-based platform operating as a technological
            service provider assisting the borrowers, essentially real estate entities to seek debt
            funding from the willing patrons through the NBFC. Use of the Platform is offered to You
            conditioned on acceptance of all the terms, conditions and notices contained in these
            Terms along with any amendments made by Altern8 at its sole discretion and posted on the
            Platform, including by way of imposing an additional charge for access to or use of a
            Service.
          </p>
          <br />
          <p>
            NOTHING CONTAINED ON THE PLATFORM SHOULD BE CONSTRUED AS AN AUTHORIZATION BY THE
            SECURITIES AND EXCHANGE BOARD OF INDIA (“SEBI”) TO SOLICIT INVESTMENTS NOR SHOULD THE
            PLATFORMS BE CONSTRUED AS A SEBI AUTHORIZED CROWDFUNDING PLATFORM OR A STOCK EXCHANGE OR
            A COLLECTIVE OR ALTERNATE INVESTMENT SCHEME, OR THEIR EQUIVALENT. THE PLATFORM MERELY
            ACTS AS A Technical Service Provider (TSP) BEING THE FACILITATOR BETWEEN THE BORROWERS
            AND THE RETAIL PATRONS ACTING THROUGH THE NBFC.
          </p>
          <br />
          <h2 className="font-bold mt-4">• Definitions and Interpretations</h2>
          <br />
          <p>
            "Altern8", "The Company", "Ourselves", "We", "Our" and "Us", refers to Ekarth Ventures
            Private Limited bearing CIN: U62099TN2024PTC169251, and other assignees, group and sister firms being the
            primary platform for real estate borrowers intending to seek debt funding through
            issuance of debt securities.
          </p>
          <br />
          <p>
            “Applicable Law” means all laws, ordinance, statutes, rules, orders, decrees,
            injunctions, licenses, permits, approvals, authorizations, consents, waivers,
            privileges, agreements and regulations of any governmental authority/court of law having
            jurisdiction over the relevant matter including any interpretations thereof, in effect.
          </p>
          <br />
          <p>
            “Terms and Conditions” means these Terms of Use, Privacy Policy, Transaction Documents
            (if any) or any other document which outlines or governs the relationship between the
            patron, borrower, NBFC and the platform regarding the use and access of Platform and its
            services.
          </p>
          <br />
          <p>
            “Patron” means any patron or lender registered with the secondary platform and who is
            willing to invest his money in the escrow or virtual account with the NBFC or directly
            subscribe to debenture or other instruments issued by borrowers on this Platform.
          </p>
          <br />
          <p>
            “Debenture Trustee” refers to the person entrusted to hold and manage the escrow or
            virtual account on behalf of all the patrons.
          </p>
          <br />
          <p>
            “Borrower” means real estate entity registered with the Platform to seek identification
            from the NBFC.
          </p>
          <br />
          <p>
            "Intellectual Property Rights" means all patents, designs and drawings, trademarks,
            service marks, logos, domain names and utility models, copyrights, inventions, brand
            names and business names and any similar rights and the benefit (subject to the burden)
            of any of the foregoing (in each case whether registered or otherwise), and includes
            applications for the grant of any of the foregoing and the right to apply for any of the
            foregoing in any part of the world.
          </p>
          <br />
          <p>
            “Confidential Information” means all communications between the Parties, and other
            material supplied to or received by any of the Parties hereto from the others which is
            either marked ‘confidential’ or is by its nature intended to be exclusively for the
            knowledge of the recipient alone, and any information concerning the affairs, the
            business, customer details, business transactions or the financial arrangements of
            Altern8 or of any Person with whom any of them is in a confidential relationship and
            shall include the terms of this Agreement and all connected documents and/or writings.
          </p>
          <br />
          <p>
            “Platform Fee” shall mean the fee due and payable to Altern8 by the borrowers as per
            terms hereof for enabling, managing, facilitating and rendering requisite technical
            services for the Debt funding transaction through the Platform.
          </p>
          <br />
          <p>
            “Secondary Platform” refers to the platform which facilitates the buying and selling of
            the units of debt instruments that are being issued through this Platform.
          </p>
          <br />
          <h2 className="font-bold mt-4">• Approval of use </h2>
          <br />
          <p>
            By accessing the Platform, registering as a borrower with the Platform, submitting any
            material to the Platform, or using any of the Services, you expressly agree that-
            <br />
            <br />
            1. You have read, understood and agreed to these Terms, and acknowledge that these Terms
            shall apply to you and be binding on you. <br />
            2. You are entering into these Terms out of your own free will and consent
          </p>
          <br />
          <p>
            Accordingly, if you wish not to accept the terms of use, you will not be able to access
            the platform or the services available on it.{' '}
          </p>
          <br />
          <h2 className="font-bold mt-4">• Services</h2>
          <br />
          <p>
            The Platform is essentially a technical service provider set up as a private limited
            company that will assist the NBFC or Patrons or other NBFCs to identify borrowers.
          </p>
          <br />
          <p>
            The main purpose of the platform is to help and provide real estate borrowers secure
            additional funding through issuance of debt instruments with the help of facilitation
            from NBFC.
          </p>
          <br />
          <p>
            The user agree and acknowledge that Altern8’s role is merely to facilitate the
            transaction between the real estate borrowers and the retail patrons backed by the NBFC
            and is in no way involved in the lending or pooling of money.
          </p>
          <br />
          <p>
            All lending happens through the escrow/virtual or nodal account of the patrons and the
            borrowersand sometimes the NBFCmay bring the loans on their books and sell the loans.
            Altern8 is in no way involved in the flow of funds, repayments, collections etc. and it
            is the sole responsibility of the borrowers to issue the debentures to the patrons
            directly in or through the NBFC in accordance with applicable laws and regulations.
          </p>
          <br />
          <p>
            Role of Altern8 is limited to borrower identification and registration, basic due
            diligence of the borrowers, credit assessment, customer service etc. with the ultimate
            responsibility being that of the NBFC.
          </p>
          <br />
          <p>
            The borrowers registers with the platform and put up for sale its Debt Instruments in
            order to receive funds through escrow or nodal account opened up with this Platform that
            is being jointly managed by the borrower and the debenture trustee, the amount is being
            used by the borrower for carrying on its operations. Hence, there is no selling or
            transfer of ownership over the real estate assets but merely lending of funds for the
            real estate companies.
          </p>
          <br />
          <p>
            In return, the companies (borrowers) issues NCDs, OCDs, Secured Notes or other eligible
            products to the patrons directly or through the NBFC, as per the relevant provisions of
            Companies Act, 2013, Companies Issue of Share Capital and Debentures Rules,2014 and SEBI
            Debenture Trustee Regulations, 1993.
          </p>
          <br />
          <h2 className="font-bold mt-4">• Eligibility to use</h2>
          <br />
          <p>
            Any company registered under the companies act or any other law for the time being in
            force, engaged primary in real estate business that is capable of issuing debt
            instruments in order to seek funding from retail patrons and is capable/competent to
            form a binding contract can register as “borrower” on the Platform.
          </p>
          <br />
          <p>
            The Services are not available to any borrower that is under insolvency or liquidation
            proceedings and has been prohibited to issue such securities by any regulatory or other
            authority or has been suspended or removed from Altern8 system by Altern8 for any reason
            whatsoever. If You are removed, You shall not be permitted to avail the Services or use
            the Platform. The services are not available to patron who has been restricted or
            prohibited from investing in securities by SEBI, RBI or any other regulatory authority
            under any law for the time being in force.
          </p>
          <br />
          <p>
            You acknowledge that Altern8 reserves the right to refuse access to use the Services
            offered at the Platform to new Users or to terminate access granted to existing Users at
            any time without according any reasons for doing so.
          </p>
          <br />
          <p>
            IF YOU DO NOT MEET THE ELIGIBILITY CRITERIA OF THIS TOU (Terms of Use), PLEASE DO NOT
            ATTEMPT TO USE ANY OF OUR SERVICES. USE OF A VIRTUAL PRIVATE NETWORK TO CIRCUMVENT THE
            RESTRICTIONS SET FORTH IN THESE TOU IS PROHIBITED.
          </p>
          <br />
          <h2 className="font-bold mt-4">• User Account, Password and Security </h2>
          <br />
          <p>
            In order to fully avail the services provided by Altern8, the borrower entity needs to
            create a separate account by providing several information like Company name, registered
            address, CIN details, person of contact etc. Unless otherwise permitted by Altern8 in
            writing, one entity may only possess one account at a time.{' '}
          </p>
          <br />
          <p>
            You acknowledge that You will be responsible for maintaining the confidentiality of the
            Account Information, and are fully responsible for all activities that occur under Your
            User Account. <br />
            <br />
            You agree to: <br />
            <br />
            (a) immediately notify Altern8 of any unauthorized use of Your Account Information or
            any other breach of security, and <br />
            (b) ensure that You exit from Your User Account at the end of each session. Altern8
            cannot and shall not be liable for any loss or damage arising from Your failure to
            comply with this Section. Further, You understand that You may be held liable for losses
            incurred by Altern8 or any other user of or visitor to the Platform due to authorized or
            unauthorized use of Your Account as a result of Your failure in keeping Your Account
            Information secure and confidential.
          </p>
          <br />
          <p>
            Altern8 reserves the right to refuse to offer access to or use of the Platform to any
            entity at its sole discretion including by changing its eligibility criteria at any
            time.
          </p>
          <br />
          <p>
            If You provide any information that is untrue, inaccurate, not current or incomplete (or
            becomes untrue, inaccurate, not current or incomplete), or Altern8 has reasonable
            grounds to suspect that such information is untrue, inaccurate, not current or
            incomplete, Altern8 has the right to suspend or terminate Your User Account and refuse
            any and all current or future use of the Platform (or any portion thereof) without
            providing any notice or according reasons for the same.
          </p>
          <h2 className="font-bold mt-4">• User Obligations </h2>
          <br />
          <p>
            You agree to use the platform and avail its services only for lawful purposes and in
            accordance with the applicable rules and regulations. Your further agree not to
            undertake any such activity that is prejudicial to the interest of the platform or of
            other users associated with the platform such that it makes the services inaccessible
            for them. You agree and undertake not to reverse engineer, modify, copy, distribute,
            transmit, display, perform, reproduce, publish, license, create derivative works from,
            transfer, or sell any information or software obtained from this Website.
            <br />
            <br />
            You undertake that your access to the Services is-
            <br />
            <br />
            (a) not prohibited by and does not otherwise violate or assist you to violate any
            domestic or foreign law, rule, statute, regulation, by-law, order, protocol, code,
            decree, or another directive, requirement, or guideline, published or in force that
            applies to or is otherwise intended to govern or regulate any person, property,
            transaction, activity, event or other matter, including any rule, order, judgment,
            directive or other requirement or guideline issued by any domestic or foreign federal,
            provincial or state, municipal, local or other governmental, regulatory, judicial or
            administrative authority having jurisdiction over Altern8, you, the Website or the
            Services, or as otherwise duly enacted, enforceable by law, the common law or equity;
            and (b) does not contribute to or facilitate any illegal activity.
          </p>
          <br />
          <p>
            During the use of the Platform or Services offered on the Platform, You shall not post,
            host, display, upload, modify, publish, transmit, update or share any information that:
            <br />
            <br />
            • Impersonate any person or entity, or falsely state or otherwise misrepresent Your
            affiliation with a person or entity;
            <br />• Publish, post, upload, distribute or disseminate any inappropriate, profane,
            defamatory, infringing, obscene, indecent or unlawful topic, name, material or
            information through any bookmark, tag or keyword;
            <br />• Upload files, material or any information in violation of the intellectual
            property rights of another person;
            <br />• Upload files, material or any information in violation of any confidentiality
            agreement with respect to a third party;
            <br />• Upload or distribute files that contain viruses, corrupted files, or any other
            similar software or programs that may damage the operation of the Platform or another's
            computer;
            <br />• Engage in any activity that interferes with or disrupts access to the Platform
            or the Services (or the servers and networks which are connected to the Platform);
            <br />• Attempt to gain unauthorized access to any portion or feature of the Platform,
            any other systems or networks connected to the Platform
          </p>
          <br />
          <h2 className="font-bold mt-4">• Representation and Warranties </h2>
          <br />
          <p>
            The user hereby agrees and warrants that the Platform, Services, Content and other
            materials are provided by Altern8 on an "as is" basis without warranty of any kind,
            express, implied, statutory or otherwise, including the implied warranties of accuracy,
            reliability or fitness for a particular purpose. To the fullest extent permissible
            pursuant to applicable law, Altern8 disclaims all warranties, express or implied,
            including but not limited to, implied warranties of merchantability and fitness for a
            particular purpose. Altern8 does not warrant that the website or the server that makes
            it available is free from viruses or other harmful components. Without limiting the
            foregoing, Altern8 makes no warranty that (i) the Platform or the Services will meet
            Your requirements or Your use of the Platform or the Services will be uninterrupted,
            timely, secure or error-free; (ii) the results that may be obtained from the use of the
            Platform, Services or materials will be effective, accurate or reliable; (iii) the
            quality of the Platform, Services or other materials will meet your expectations; or
            that (iv) any errors or defects in the Platform, Services or other materials will be
            corrected. No advice or information, whether oral or written, obtained by You from
            Altern8 or through or from use of the Services shall create any warranty not expressly
            stated in the Terms of Use.
          </p>
          <br />
          <p>
            The borrower entity represents, warrants and covenants that-
            <br />
            <br />
            • It is a bona fide entity registered under the law engaged primarily in real estate
            business and authorized to issue debentures to the retail patrons and has not be
            liquidated or disqualified under the law.
            <br />• The specified debentures as above are completely genuine, bona fide debt
            securities raised by it and are free from any lien or encumbrances. The purchase price
            for each unit represents the issue price of the debentures that may be premium or
            discounted price.
            <br />• the right, title and interest in the Debentures to be assigned to/created in
            favour of the Patron(s) hereunder is absolute, clear, solely in favour of the Patron(s).
            <br />• That all the documents representing the financial position of the company have
            been duly published in public domain including but not limited to audit report, profit
            and loss account, annual accounts etc.
            <br />• Thereare no legal, quasi-legal, administrative, arbitration, mediation,
            conciliation or other proceedings, claims, actions, governmental investigations, orders,
            judgments or decrees of any nature made, existing, threatened, anticipated or pending
            against itself which will adversely impact the Transaction.
            <br />• The terms of the debenture issue have been duly notified in accordance with the
            applicable laws and are not prejudicial to the interest of the patrons to such issue.
            <br />• It will provide the Platform a Post dated Cheque for each transaction executed
            through the Platform as a guarantee against the repayments. Altern8 shall have the sole
            right to enforce these PDCs in case of any default in repayment or other terms of issue.
          </p>
          <br />
          <h2 className="font-bold mt-4">• Terms of Debenture Issue </h2>
          <br />
          <p>
            Prior to availing any funding through the Platform, the borrower needs to create a
            virtual escrow account with the Platform by providing KYC due diligence and all the
            relevant details as required for the creation of such account. Each transaction executed
            through the Platform shall be facilitated through this account and the patrons money
            invested towards the debt securities will also be received through these accounts only.
            The borrower the need to provide the details and pricing about its debentures that may
            be a discounted or premium price along with all the terms of issue including but not
            limited to the terms of repayment, interest payment, interest cutoff date, maturity
            period, redemption date etc. Altern8 is responsible to share all these details with the
            patrons registered on the secondary platform to enable the potential patrons invest in
            these debentures. The payment transactions between the borrower and the patron or the
            NBFC will solely be facilitated through the escrow account. A specific debenture
            agreement shall be executed between the borrower and the patron as well as between the
            borrower and the NBFC including the terms of repayments, events of default, consequences
            of default and the rights and obligations of the parties.
          </p>
          <br />
          <h2 className="font-bold mt-4">• Intellectual Property Rights </h2>
          <br />
          <p>
            Unless otherwise expressly provided by the terms of the platform, all the Intellectual
            Property Rights in the Platform and its content are owned by Altern8 and no user is
            entitled to use these intellectual property rights except as consented by the platform
            through these terms or any other policy for the time being. All content and materials
            including but not limited to text, graphics, website name, code, images, and logos are
            the intellectual property of Altern8 and are protected by applicable copyright and
            trademark law. Any inappropriate use or transmission of any content on this site is
            strictly prohibited unless specifically authorized to do so. Except as expressly
            provided herein, You acknowledge and agree that You shall not use, in any manner
            whatsoever, any Content through any medium without obtaining the necessary authorization
            from Altern8 or thirty party owners of such Content. You agree that by use of the
            Platform or by availing the Services You shall not obtain any right or interest on the
            materials and Content. However, Altern8 may assign or license its trademark or other
            intellectual property rights to any third party for promotional or marketing purposes.
          </p>
          <br />
          <h2 className="font-bold mt-4">• Royalty </h2>
          <br />
          <p>
            Altern8 reserves exclusive ownership rights over the Intellectual Property associated
            with the platform and the Patron acknowledges that they are granted a limited,
            non-exclusive license to use the Platform in accordance with these Terms of Use. This
            license does not transfer any ownership rights of the IP to the users. Users of the
            platform are required to pay specific royalties to the platform for using the technical
            services and the IPs of the platform. The royalties are fees for the service of using
            Altern8’s proprietary technology and intellectual property, which facilitate the
            transactions between borrowers and patrons.Royalties provided for availing the services
            of the Platform shall be exclusive of any taxes since the same is exempted in accordance
            with the Provisions of the Income Tax Act.
          </p>
          <br />
          <h2 className="font-bold mt-4">• Escrow Account </h2>
          <br />
          <p>
            The Platform facilitates the creation of escrow accounts for the convenience of payments
            made by the patrons and borrowers for each transaction executed through it. However,
            such facilitation shall not be construed as an agent-principal relationship between the
            Platform and the borrower.
            <br />
            By availing the services of the Platform, the borrower acknowledges to provide Altern8
            special power of attorney to manage its escrow account just for the sake of convenience.
            By consenting the same, the Platform shall have the absolute authority to enter into
            specific agreements with the escrow or virtual account provider for the creation of such
            account on behalf of the borrower.{' '}
          </p>
          <br />
          <h2 className="font-bold mt-4">• Modification of terms </h2>
          <br />
          <p>
            Altern8 reserves the rights, at its sole discretion, to amend, alter, modify, change,
            add or remove any portion of the Terms of Use or the Privacy Policy, in whole or in
            part, at any time.
            <br />
            The revised Terms of Use shall be made available on the Platform. You agree to take the
            responsibility to be aware of the updated terms of use by frequently visiting the
            website and Altern8 shall not be responsible to communicate you about any changes made
            to the terms and conditions of use.
            <br />
            Your continued use of the Platform and/or the Services made available on or through the
            Platform after any changes to the Terms of Use or the Privacy Policy are posted will be
            considered acceptance of such changes. You can determine when Altern8 last modified the
            Terms of Use by referring to the "Last Updated" legend herein.
          </p>
          <br />
          <h2 className="font-bold mt-4">• Fees and Charges </h2>
          <br />
          <p>
            The platform reserves the right to charge any registration pr service fee from the
            borrower entities for the facilitation of its issue. Moreover, whenever the patron
            invests in any NCDs through the NBFC, the platform may charge commission fee as
            specified on the platform for such transaction for acting as a facilitator between the
            borrower and the patron.
          </p>
          <br />
          <h2 className="font-bold mt-4">• Data Protection and Privacy </h2>
          <br />
          <p>
            The User hereby consents, expresses and agrees that they have read and fully understands
            the Privacy Policy of Altern8 in respect of access to the Platform.
            <br />
            You further consent that the terms and contents of such Privacy Policy are acceptable to
            You and the platform reserves the right to collect and process user data from you.{' '}
            <br />
            Altern8 hereby undertakes to protect your data with integrity and safety measures and
            shall implement and maintain appropriate technical and organizational measures to
            protect personal data against unauthorized or unlawful processing, accidental loss,
            destruction, or damage.
          </p>
          <br />
          <h2 className="font-bold mt-4">• Confidentiality </h2>
          <br />
          <p>
            Subject to the specific permissions in these Terms of Use, both parties will protect
            each other’s Confidential Information from unauthorized use, access, or disclosure,
            using at least the same level of care as they use to protect their own Confidential
            Information, but no less than a reasonable standard of care.
            <br />
            Except as expressly allowed by these Terms of Use, each party may use the other’s
            Confidential Information only to exercise their rights and fulfill their obligations
            under these Terms of Use. "Confidential Information" refers to any information labeled
            as "confidential" (or similarly) or that a reasonable person would consider confidential
            given its nature and the circumstances of disclosure.
            <br />
            However, Confidential Information does not include information that: (a) was already
            known to the receiving party at the time of disclosure; (b) was obtained from a third
            party without an obligation of confidentiality; (c) becomes publicly available without
            breaching these Terms of Use; or (d) is independently developed by the receiving party
            without using the disclosing party’s Confidential Information.
          </p>
          <br />
          <h2 className="font-bold mt-4">• Governing Law </h2>
          <br />
          <p>
            These terms and conditions shall be governed by and construed in accordance with the
            laws of India as applicable for the time being in force. Subject to the generality of
            the foregoing, these terms and conditions shall be subject to the provisions of
            Companies Act, the Debenture rules, SEBI rules and regulations as well as RBI
            regulations for NBFCs and issuance of NCDs.
          </p>
          <br />
          <h2 className="font-bold mt-4">• Dispute Resolution </h2>
          <br />
          <p>
            The determination of existence of any disputes, the nature of the disputes and how it
            should be handled relating to these terms and conditions shall be decided by Altern8.
            Subject to the above, any dispute arising out of the services provided by the platform,
            be it between the patron and the platform or between borrower and the platform or
            between the NBFC and the platform, the dispute shall be resolved through award of sole
            arbitrator to be appointed by both the parties in accordance with its rules and subject
            to the provisions of the Arbitration and Conciliation Act, 1996 as amended from time to
            time.
            <br />
            The venue of Arbitration shall be at Chennai and the language shall be English.{' '}
          </p>
          <br />
          <h2 className="font-bold mt-4">• Limitation of Liability </h2>
          <br />
          <p>
            Altern8 does not guarantee that the borrower will be capable of getting the potential
            investor as per its expectations. The Platform merely acts as a facilitator between the
            borrower and the patron and has no liability to compensate if the borrower fails to get
            any potential patron for its debenture issue or fails to get the minimum subscription as
            per the applicable law.
            <br />
            Altern8 will not be liable for any direct, indirect, incidental, consequential or
            exemplary loss or damages which may be incurred by you as a result of using our
            Resources, or as a result of any changes, data loss or corruption, cancellation, loss of
            access, or downtime to the full extent that applicable limitation of liability laws
            apply.
            <br />
            <br />
            To the fullest extent permitted by applicable law, Altern8 shall not be liable to you
            for any damages arising from:
            <br />
            <br /> (i) errors, mistakes, or inaccuracies in content, <br />
            (ii) personal injury or property damage resulting from your access to and use of the
            services, <br />
            (iii) unauthorized access to or use of our servers and any personal information stored
            therein, <br />
            (iv) any interruption or cessation of transmission to or from our servers, <br />
            (v) bugs, viruses, trojan horses, or similar issues transmitted through the services by
            any third party, <br />
            (vi) loss of your data or content from the services, <br />
            (vii) errors or omissions in any content or any loss or damage resulting from your use
            of any content posted, transmitted, or made available through the services, whether
            based on warranty, contract, tort, or any other legal theory, and whether or not we were
            advised of the possibility of such damages, <br />
            (viii) disclosure of information according to these terms or our privacy policy, <br />
            (ix) your failure to keep your password or account details secure and confidential, or{' '}
            <br />
            (x) loss or damage incurred by you due to reliance on the completeness, accuracy, or
            existence of any advertising, or due to any relationship or transaction between you and
            any advertiser or sponsor whose advertising appears on the services. In no event shall
            we be liable to you for any indirect, incidental, special, punitive, exemplary, or
            consequential damages, including but not limited to loss of profit, goodwill, business
            reputation, data, or other intangible losses.
          </p>
          <br />
          <h2 className="font-bold mt-4">• Indemnity </h2>
          <br />
          <p>
            The borrower agrees and undertakes to severally keep and hold the Patron(s), and/or
            Altern8 and their respective directors, officers, shareholders, employees, agents and
            representatives (collectively, the “Indemnified Parties”) indemnified and harmless
            against all costs, expenses, claims (including third party claims), liabilities,
            demands, prosecutions, damages and proceedings which may be caused to or suffered by or
            made or taken against any of the Indemnified Parties arising out of: <br />
            <br />
            the breach of any of its representations and warranties as contained in this Agreement;
            <br />
            default or non-performance in regards to payment obligation
          </p>
          <br />
          <h2 className="font-bold mt-4">• Termination </h2>
          <br />
          <p>
            Altern8 may terminate your access to all or any part of the platform at any time with or
            without cause, with or without notice, effective immediately, which may result in the
            loss and damage of all the information and ongoing transactions you may have in
            connection with the platform.
            <br />
            <br />
            Subject to the generality of the foregoing, Altern8 may terminate your access to the
            platform if-
            <br />
            <br />
            • You have violated these terms of use or any other policy of the platform such as
            privacy policy.
            <br />• You have acted in an illegal or unethical manner prejudicial to the interest of
            other users/ borrowers on the platform, or against the interest of platform itself.
            <br />• You have violated any of the applicable rules and regulations regarding issue of
            NCDs as prescribed under applicable laws such as Companies Act, Companies Share Capital
            and Debenture Rules 2014, or any SEBI or RBI regulations as applicable from time to
            time.
            <br />• Any suspected illegal, fraudulent or abusive activity through your user account
            shall also be a ground for termination.
            <br />• Any other activity incidental to the above stated activities, which in the
            opinion of Altern8, is liable for termination.
            <br />
            <br />
            If you object to any Terms and Conditions, your only recourse is to: (a) discontinue use
            of the Platform or the Services; and (b) notify Altern8 of such discontinuance. Please
            note that such termination shall only govern Your usage of the Platform and any Services
            offered to You by an affiliate of Altern8 (be it NBFC) or a third party shall continue
            to be governed by the terms agreed in such individual service agreements.
          </p>
          <br />
          <h2 className="font-bold mt-4">• Report Abuse </h2><br/>
          <p>In the event You come across any abuse or violation of these Terms of Use including any
          Privacy Policy or Additional Terms or if You become aware of any objectionable content on
          the Platform, please report immediately to Altern8 customer support.</p><br/>
          <h2 className="font-bold mt-4">• Communications</h2><br/>
          <p>
            Upon your express consent by way of clicking on the check box provided on the platform
            for this purpose, You expressly agree to receive communications (including promotional
            materials) by way of telephones, WhatsApp, RCS, SMS, e-mails, etc., from Altern8
            relating to any Services provided through the Platform.
          </p><br/>
          <h2 className="font-bold mt-4">• Third party sites </h2><br/>
          <p>
            The Website or the mails for communication may contain links to third-party
            websites. However, these links are merely for advertisement purposes only and the
            company has no connection or affiliation with any of these third party sites or their
            products. The company neither provides for the endorsement of any other product or
            services through its platform. The provision of Third-Party Content is for general
            informational or advertisement purposes only. In no event shall Altern8 be responsible
            for the information contained on any Third-Party Sites or your use of or inability to
            use any Third-Party Sites. You acknowledge and agree that Altern8 shall not be liable or
            responsible, directly or indirectly, for any damage or loss caused through any
            third-party website or resource.
          </p><br/>
          <h2 className="font-bold mt-4">• Miscellaneous </h2><br/>
          <p>
            Notice: All notices to Altern8 shall be served by email or by general notification on
            the Platform. Any notice to be provided to Altern8 pursuant to the Terms of Use should
            be sent to customer support (___________). Entire Agreement:These Terms of Use, together
            with the Privacy Policy constitute the entire agreement between you and Altern8 in
            relation to your use of the Platform and supersede all previous agreements in respect of
            your use of the Platform. Please note, however, that other aspects of your use of
            Services may be governed by additional agreements. If any term of this Terms of Use
            expressly conflicts with any term of any individual service agreement executed between
            borrower, patron or the NBFC, such conflict will be resolved at our sole discretion.
            Severability: If for any reason, a court of competent jurisdiction finds any provision
            of the Term of Use, or portion thereof, to be unenforceable, that provision shall be
            enforced to the maximum extent permissible so as to give effect to the intent of the
            parties as reflected by that provision, and the remainder of the Terms of Use shall
            continue in full force and effect. Waiver: Altern8’s failure to enforce any provision of
            this Terms of Use shall not be deemed to be a waiver of such provision nor of the right
            to enforce such provision.
          </p>
          Contact: If you have any queries or doubt regarding the terms of use, please reach the
          customer support of Altern8 at (___).
          <br />
        </div>
      </div>
      <JoinUsSection />
      <Footer />
      <FloatingButton />
    </div>
  );
};

export default TermsCondition;
