import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';
import "react-toastify/dist/ReactToastify.css";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Altern8",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Altern8</title>
      </head>
      <body className={`${figtree.className}`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
