import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';

const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Altern8",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.className}`}>
        {children}
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
