export const images = [
  "Aditya birla sun life insurance.png",
  "APGB.png",
  "APGVB.png",
  "Arunachal Pradesh Rural Bank.png",
  "aryavart.png",
  "Assam Gramin.png",
  "Axis_Bank_logo.png",
  "Bajaj allianz insurance.png",
  "bajaj finserv bank.png",
  "bank-of-baroda-logo-vector.png",
  "bank-of-india-boi-logo-vector.png",
  "Bank_of_Maharashtra_logo.png",
  "Baroda gujarat.png",
  "Baroda Rajasthan.png",
  "Baroda up.png",
  "bharti axa.png",
  "cams.png",
  "canara bank.png",
  "canara hsbc.png",
  "cdsl.png",
  "Cental Bank of India.png",
  "Central BANK.png",
  "Central_Depository_Services_(India)_Limited.png",
  "Chaitanya Godavri.png",
  "city union bank.png",
  "dakshin Bihar Grameen.png",
  "edelweiss tokio life.png",
  "ellaquai dehati bank.png",
  "federal bank.png",
  "fincare.png",
  "future generation life.png",
  "hdfc ergo.png",
  "HDFC.png",
  "himachal pradesh grameen bank.png",
  "icici lombard nibhaye vaade.png",
  "icici prudential.png",
  "ICICI.png",
  "idfc.png",
  "india overseas.png",
  "indiafirst-life-insurance.png",
  "Indian Bank.png",
  "Indusland.png",
  "Jammu and Kashmir Grameen Bank.png",
  "karnataka Gramin Bank.png",
  "Karur Vysya.png",
  "Kerala Gramin bank.png",
  "kotak life insurance.png",
  "kotak.png",
  "liberty general insurance.png",
  "madhyanchal Gramin.png",
  "ManipalCigna.png",
  "Meghalaya Rural Bank.png",
  "Mizoram Rural Bank.png",
  "NSDL.png",
  "pashchim.png",
  "pnb.png",
  "pramerica.png",
  "Prathma UP gramin Bank.png",
  "Protean.png",
  "puduvai pay.png",
  "punjab and sind.png",
  "punjab gramin bank.png",
  "Raheja qbe.png",
  "Rajasthan marudhara bank.png",
  "sarva haryana gramin bank.png",
  "Saurashtra gramin bank.png",
  "sbi general.png",
  "SBI life insurance_Logo.png",
  "SBI.png",
  "sgb-logo-strip.png",
  "Shriram Life Insurance Logo.png",
  "South Indian.png",
  "Tata aia.png",
  "tata aig insurance.png",
  "tripura gramin bank.png",
  "UCO.png",
  "Union BANK.png",
  "utkal gramin bank.png",
  "uttrakhand gramin bank.png",
  "vidharbha konkan.png",
  "Yes Bank.png",
]