name: Next.js Build Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: "Image version"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Clean caches first
      - name: Clean caches
        run: |
          rm -rf .next
          rm -rf node_modules
          git rm -r --cached .

      - name: Install dependencies
        run: bun install

      - name: Run Next.js build
        run: bun run build

    #   - name: Run tests
    #     run: bun test
