name: Next.js Build Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: "Image version"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure git to be case sensitive
        run: git config --global core.ignorecase false

      - name: Debug file structure
        run: |
          echo "Current directory structure:"
          ls -R

      - name: Fix specific folders
        run: |
            git mv -f Utils utils || true
            git mv -f Contexts contexts || true

      - name: Checkout code
        uses: actions/checkout@v3

      # Force git to acknowledge case changes
      - name: Fix case sensitivity issues
        run: |
          git ls-files | while read -r file; do
            dir=$(dirname "$file")
            if [ "$dir" != "." ]; then
              mkdir -p "$dir"
            fi
            # Rename the file to a temporary name and back to force git to acknowledge case changes
            git mv -f "$file" "$file.tmp" || true
            git mv -f "$file.tmp" "$file" || true
          done

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Clean caches first
      - name: Clean caches
        run: |
          rm -rf .next
          rm -rf node_modules
          git rm -r --cached .

      - name: Install dependencies
        run: bun install

      - name: Run Next.js build
        run: bun run build

    #   - name: Run tests
    #     run: bun test
